- name: firewalld is disabled
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: iptables services are installed
  yum:
    name: iptables-services
    state: present

- name: iptables v4 rules are up
  template:
    src: ipv4.rules.j2
    dest: /etc/sysconfig/iptables
    mode: 0700
  vars:
    PIF: "{{ ansible_default_ipv4.interface }}"
  notify: iptables is restarted

- name: iptables v6 rules are up
  template:
    src: ipv6.rules.j2
    dest: /etc/sysconfig/ip6tables
    mode: 0700
  vars:
    PIF: "{{ ansible_default_ipv4.interface }}"
  notify: iptables is restarted

- name: iptables service is activated
  service:
    name: iptables
    state: started
    enabled: yes
