- name: rpm fusion is enabled
  yum:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
    state: present

- name: required packages are present
  yum:
    name: "{{ required_packages }}"
    state: present
